FROM node:20.12-slim
WORKDIR /app
COPY ./skyvern-frontend /app
COPY ./entrypoint-skyvernui.sh /app/entrypoint-skyvernui.sh
RUN chmod +x /app/entrypoint-skyvernui.sh
RUN npm install
ENV VITE_API_BASE_URL=/api/v1
ENV VITE_WSS_BASE_URL=wss://ui.skyvern.wmappliances.cloud/api/v1
ENV VITE_ARTIFACT_API_BASE_URL=https://ui.skyvern.wmappliances.cloud:9090
# A chave API será fornecida via variáveis de ambiente no Easypanel
CMD [ "/bin/bash", "/app/entrypoint-skyvernui.sh" ]
