FROM node:20.12-slim
WORKDIR /app
COPY ./skyvern-frontend /app
COPY ./entrypoint-skyvernui.sh /app/entrypoint-skyvernui.sh
RUN chmod +x /app/entrypoint-skyvernui.sh
RUN npm install
ENV VITE_API_BASE_URL=http://skyvern.wmappliances.cloud/api/v1
ENV VITE_WSS_BASE_URL=ws://skyvern.wmappliances.cloud/api/v1
ENV VITE_ARTIFACT_API_BASE_URL=http://skyvern.wmappliances.cloud:9090
ENV VITE_API_KEY=AIzaSyCxAEw7Mkn5UpHuPtESrN_22AakcjlhJ1k
CMD [ "/bin/bash", "/app/entrypoint-skyvernui.sh" ]
